AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  envelGetUsers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::562144647687:role/service-role/envelUserRds'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /envelGetUsers
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api4:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api5:
          Type: Api
          Properties:
            Path: /getusers
            Method: GET
        Api6:
          Type: Api
          Properties:
            Path: /getusers
            Method: OPTIONS
        Api7:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
